repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: trailing-whitespace
      exclude: ^tests/unit_tests/test_formatters.py
    - id: flake8
    - id: check-yaml
